- name: passing variable value using filters
  hosts: local
  connection: local
  vars:
   names: sowjanya , rishika , mounika , sita
   tagsMap:
      name: ansible
      project: roboshop
      component: catalogue
   tagsList: [
        {
            "key": "name",
            "value": "ansible"
        },
        {
            "key": "project",
            "value": "roboshop"
        },
        {
            "key": "component",
            "value": "catalogue"
        }
    ]

  tasks:
  - name: passing variable value using filters
    ansible.builtin.debug:
       msg: " hi sowjanya, {{ greeting | default('good morning') }}"
    ansible.builtin.debug:
      msg: "{{ names | split(',') }}"
    ansible.builtin.debug:
      msg: "{{ tagsMap | dict2items }}"
    ansible.builtin.debug:
      msg: "{{ tagsList | items2dict }}"
    
    ansible.builtin.set_fact: # setting the variable dynamically
      student_yaml: "{{ lookup('file', 'students.yaml' ) | from_yaml }}"

  
    ansible.builtin.debug:
      msg: "{{ student_yaml | to_nice_json  }}"

