- name: installing nginx
  hosts: local
  connection: local
  tasks:
  - name: installing nginx in localhost
    ansible.builtin.package:
     name: nginx
     state: present

  - name: starting nginx
    ansible.builtin.service:
     name: nginx
     state: started