- name: printing variables
  hosts: local
  connection: local
  vars:
   trainer: "sowjanya"
   course: "aws-devops"
  tasks:
  - name: printing above defined variables
    vars:
     course: "ansible"
    ansible.builtin.debug:
     msg: "trainer is {{ trainer }} , course is {{ course }}"